apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: flaskwebapp-mysql
  namespace: dev-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskwebapp-mysql
  template:
    metadata:
      labels:
        app: flaskwebapp-mysql
    spec:
      containers:
      - image: 10.1.1.240:8083/flaskwebapp-mysql
        name: flaskwebapp-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: mysql-database
        - name: MYSQL_USER
          valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: nexus-repo-secret

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlflask-service
  namespace: dev-team
spec:
  selector:
    app: flaskwebapp-mysql
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: dev-team
data:
  database_url: mysqlflask-service