apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: nadiaaguerbaoui1/flask-app-image:latest
 
        env:
        - name: DB_HOST
          value: mysql-service
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30055
