apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: nadiaaguerbaoui1/mysql-app-image:latest
        ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlflaskservice
  namespace: default
spec:
  selector:
    app: mysql
  ports:
  - name: mysqlflaskservice
    port: 3306
    targetPort: 3306
  clusterIP: None
  type: ClusterIP
