apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlflaskservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysqlflaskservice
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlflaskservice
    spec:
      containers:
      - name: mysqlflaskservice
        image: nadiaaguerbaoui1/mysql-app-image:latest
        ports:
        - containerPort: 3306
          name: mysqlflaskservice
    
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlflaskservice
  namespace: default
spec:
  selector:
    app: flask-mysql
  ports:
  - name: mysqlflaskservice
    port: 3306
    targetPort: 3306
  clusterIP: None
  type: ClusterIP
