apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlflaskservice
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysqlflaskservice
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlflaskservice
      containers:
      - name: mysqlflaskservice
        image: nadiaaguerbaoui1/mysql-app-image:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: flask-mysql-secrets
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
          name: mysqlflaskservice
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlflaskservice
  namespace: default
spec:
  selector:
    app: flask-mysql
  ports:
  - name: mysqlflaskservice
    port: 3306
    targetPort: 3306
  clusterIP: None
  type: ClusterIP
